server:
  port: 8201

spring:
  application:
    name: proxy-zuul


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    instance-id: ${spring.application.name}

info:
  remark: 这是一个网关
  author: candle
zuul:
  routes:
    provider:
      serviceId: provider
      path: /provider/**
  ignored-services: provider