server:
  port: 80
spring:
  application:
    name: comsumer-80
  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/


